name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: action/configure-pages@v4
      - name: Upload artifact
        uses: action/upload-pages-artifact@v3
        with:
          path: '.'
      - name: Deploy to GitHubPages
        uses: action/deploy-pages@v4
    outputs:
      page_url: ${{ steps.deployment.outputs.pages-url }}
